trying to improve workflow

diff --git a/.github/workflows/build-lint-format.yml b/.github/workflows/build-lint-format.yml
--- a/.github/workflows/build-lint-format.yml
+++ b/.github/workflows/build-lint-format.yml
@@ -13,51 +13,64 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Setup Checkout
-      uses: actions/checkout@v4
+      - name: Setup Checkout
+        uses: actions/checkout@v4
 
-    - name: Setup Go
-      uses: actions/setup-go@v2
-      with:
-        go-version: '1.22.6'
+      - name: Setup Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: '1.22.6'
 
-    - name: Install dependencies
-      run: go mod download
+      - name: Install dependencies
+        run: go mod download
 
-    - name: Install Templ
-      run: go install github.com/a-h/templ/cmd/templ@latest
+      - name: Install Templ
+        run: go install github.com/a-h/templ/cmd/templ@latest
 
-    - name: Install air
-      run: go install github.com/air-verse/air@latest
+      - name: Install air
+        run: go install github.com/air-verse/air@latest
 
-    - name: Run Server
-      run: make run-silent
+      - name: Run Server
+        run: make run-silent
 
-    - name: Send Request
-      run: |
-        API_URL="http://127.0.0.1:8080/status"
-        STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $API_URL)
-        if [ $STATUS_CODE -eq 200 ]; then
+      - name: Send Request
+        run: |
+          API_URL="http://127.0.0.1:8080/status"
+          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $API_URL)
+          if [ $STATUS_CODE -eq 200 ]; then
             echo "API is deployed and responding with status code 200 (OK)"
-        else
+          else
             echo "Error: API deployment failed. Received status code: $STATUS_CODE"
             exit 1
-        fi
+          fi
 
   lint-and-format:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Setup Checkout
-      uses: actions/checkout@v4
+      - name: Setup Checkout
+        uses: actions/checkout@v4
 
-    - name: Setup Go
-      uses: actions/setup-go@v2
-      with:
-        go-version: '1.22.6'
+      - name: Setup Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: '1.22.6'
 
-    - name: Run gofmt
-      run: gofmt -l -w .
+      - name: Setup golangci-lint
+        uses: golangci/golangci-lint-action@v6
+        with:
+          version: v1.59
 
-    - name: Run golint
-      run: golint ./...
+      - name: Run golangci-lint
+        run: golangci-lint run ./...
+
+      - name: Run gofmt
+        run: |
+          gofmt -l -w .
+          if [ $? -eq 0 ]; then
+            echo "Formatting completed successfully."
+          else
+            echo "Formatting encountered an error."
+            exit 1
+          fi
+
